version: '3.8'

services:
  # دیتابیس
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: adaptive
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  # کش
  redis:
    image: redis:7-alpine

  # برنامه اصلی
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
